"""Bounded LLM operation contracts."""

from llm.gateway import (
    FakeLLMClient,
    LLMGateway,
    LLMGatewayError,
    LLMCallTrace,
    LLMOperation,
    LLMRequest,
    LLMResponse,
)
from llm.factory import build_openai_gateway
from llm.operations import (
    ChatReply,
    ChatReplyInput,
    IntentClassificationInput,
    PeriodAnalysisReply,
    PeriodAnalysisReplyInput,
    PeriodRequest,
    PeriodRequestInput,
    VisualizationIntent,
    VisualizationIntentInput,
    VisualizationIntentRevisionInput,
    WorkoutReply,
    WorkoutReplyInput,
    WorkoutReference,
    WorkoutReferenceInput,
    classify_intent,
    extract_visualization_intent,
    extract_workout_reference,
    interpret_period_request,
    revise_visualization_intent,
    write_chat_reply,
    write_period_analysis_reply,
    write_workout_reply,
)
from llm.openai_client import OpenAIClientConfig, OpenAIResponsesClient

__all__ = [
    "ChatReply",
    "ChatReplyInput",
    "FakeLLMClient",
    "IntentClassificationInput",
    "LLMGateway",
    "LLMGatewayError",
    "LLMCallTrace",
    "LLMOperation",
    "LLMRequest",
    "LLMResponse",
    "OpenAIClientConfig",
    "OpenAIResponsesClient",
    "PeriodAnalysisReply",
    "PeriodAnalysisReplyInput",
    "PeriodRequest",
    "PeriodRequestInput",
    "build_openai_gateway",
    "VisualizationIntent",
    "VisualizationIntentInput",
    "VisualizationIntentRevisionInput",
    "WorkoutReply",
    "WorkoutReplyInput",
    "WorkoutReference",
    "WorkoutReferenceInput",
    "classify_intent",
    "extract_visualization_intent",
    "extract_workout_reference",
    "interpret_period_request",
    "revise_visualization_intent",
    "write_chat_reply",
    "write_period_analysis_reply",
    "write_workout_reply",
]
