"""SQLite foundation helpers for Aimo."""

from storage.repositories import (
    ActiveWorkoutRepository,
    AttachmentRecord,
    AttachmentsRepository,
    ChannelRecord,
    ChannelsRepository,
    DebugTraceEventRecord,
    DebugTraceRecord,
    DebugTraceRepository,
    HeartRateZoneRecord,
    HeartRateZonesRepository,
    HistoryEventRecord,
    HistoryRepository,
    RenderedArtifactRecord,
    RenderedArtifactsRepository,
    UserRecord,
    UsersRepository,
    WorkoutPointRecord,
    WorkoutRecord,
    WorkoutStreamRecord,
    WorkoutStreamsRepository,
    WorkoutsRepository,
)
from storage.sqlite import StorageError, load_schema, open_connection, transaction
from storage.unit_of_work import RepositoryBundle, UnitOfWork, build_repositories, open_database

__all__ = [
    "ChannelRecord",
    "ChannelsRepository",
    "ActiveWorkoutRepository",
    "AttachmentRecord",
    "AttachmentsRepository",
    "DebugTraceEventRecord",
    "DebugTraceRecord",
    "DebugTraceRepository",
    "HeartRateZoneRecord",
    "HeartRateZonesRepository",
    "HistoryEventRecord",
    "HistoryRepository",
    "RenderedArtifactRecord",
    "RenderedArtifactsRepository",
    "RepositoryBundle",
    "StorageError",
    "UnitOfWork",
    "UserRecord",
    "UsersRepository",
    "WorkoutPointRecord",
    "WorkoutRecord",
    "WorkoutStreamRecord",
    "WorkoutStreamsRepository",
    "WorkoutsRepository",
    "build_repositories",
    "load_schema",
    "open_database",
    "open_connection",
    "transaction",
]
